In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Cars93_miss (1).csv")
df

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,None,Front,...,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17.0,21.0,None,Front,...,7.0,187.0,115.0,72.0,38.0,34.0,NaN,3960.0,NaN,Volkswagen Eurovan
89,Volkswagen,Passat,Compact,17.6,20.0,22.4,21.0,30.0,None,Front,...,5.0,180.0,103.0,67.0,35.0,31.5,14.0,2985.0,non-USA,Volkswagen Passat
90,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18.0,25.0,None,Front,...,4.0,159.0,97.0,66.0,36.0,26.0,15.0,2810.0,non-USA,Volkswagen Corrado
91,Volvo,240,Compact,21.8,22.7,23.5,21.0,28.0,Driver only,Rear,...,5.0,190.0,104.0,67.0,37.0,29.5,14.0,2985.0,non-USA,Volvo 240
92,NaN,850,Midsize,24.8,26.7,28.5,20.0,28.0,Driver & Passenger,Front,...,5.0,184.0,105.0,69.0,38.0,30.0,15.0,3245.0,non-USA,Volvo 850

In [3]:
df.columns

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [4]:
use_col= [ 'Price','Cylinders', 'EngineSize', 'Horsepower', 'RPM',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
        'Weight',]

In [5]:
dff =df[use_col]
dff

,Price,Cylinders,EngineSize,Horsepower,RPM,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Weight
0,15.9,4,1.8,140.0,6300.0,13.2,5.0,177.0,102.0,68.0,2705.0
1,33.9,6,3.2,200.0,5500.0,18.0,5.0,195.0,115.0,71.0,3560.0
2,29.1,6,2.8,172.0,5500.0,16.9,5.0,180.0,102.0,67.0,3375.0
3,37.7,6,NaN,172.0,5500.0,21.1,6.0,193.0,106.0,NaN,3405.0
4,30.0,4,3.5,208.0,5700.0,21.1,4.0,186.0,109.0,69.0,3640.0
...,...,...,...,...,...,...,...,...,...,...,...
88,19.7,5,2.5,109.0,4500.0,21.1,7.0,187.0,115.0,72.0,3960.0
89,20.0,4,2.0,134.0,5800.0,18.5,5.0,180.0,103.0,67.0,2985.0
90,23.3,6,2.8,178.0,5800.0,18.5,4.0,159.0,97.0,66.0,2810.0
91,22.7,NaN,2.3,114.0,5400.0,15.8,5.0,190.0,104.0,67.0,2985.0
92,26.7,5,2.4,168.0,6200.0,19.3,5.0,184.0,105.0,69.0,3245.0

In [6]:
dff.isna().sum()

Price                 2
Cylinders             5
EngineSize            2
Horsepower            7
RPM                   3
Fuel.tank.capacity    8
Passengers            2
Length                4
Wheelbase             1
Width                 6
Weight                7
dtype: int64

In [7]:
use_coll= ['Cylinders',
       'EngineSize', 'Horsepower', 'RPM',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
        'Weight',]
dff[use_coll] = dff[use_coll].fillna(0)

C:\Users\asus\AppData\Local\Temp\ipykernel_14968\1082227336.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff[use_coll] = dff[use_coll].fillna(0)

In [8]:
#dff['Min.Price']= dff['Min.Price'].fillna(dff['Min.Price'].mean())
dff['Price']= dff['Price'].fillna(dff['Price'].mean())
#dff['Max.Price']= dff['Max.Price'].fillna(dff['Max.Price'].mean())
dff.isna().sum()

C:\Users\asus\AppData\Local\Temp\ipykernel_14968\2998687622.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['Price']= dff['Price'].fillna(dff['Price'].mean())

Price                 0
Cylinders             0
EngineSize            0
Horsepower            0
RPM                   0
Fuel.tank.capacity    0
Passengers            0
Length                0
Wheelbase             0
Width                 0
Weight                0
dtype: int64

In [9]:
dff

,Price,Cylinders,EngineSize,Horsepower,RPM,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Weight
0,15.9,4,1.8,140.0,6300.0,13.2,5.0,177.0,102.0,68.0,2705.0
1,33.9,6,3.2,200.0,5500.0,18.0,5.0,195.0,115.0,71.0,3560.0
2,29.1,6,2.8,172.0,5500.0,16.9,5.0,180.0,102.0,67.0,3375.0
3,37.7,6,0.0,172.0,5500.0,21.1,6.0,193.0,106.0,0.0,3405.0
4,30.0,4,3.5,208.0,5700.0,21.1,4.0,186.0,109.0,69.0,3640.0
...,...,...,...,...,...,...,...,...,...,...,...
88,19.7,5,2.5,109.0,4500.0,21.1,7.0,187.0,115.0,72.0,3960.0
89,20.0,4,2.0,134.0,5800.0,18.5,5.0,180.0,103.0,67.0,2985.0
90,23.3,6,2.8,178.0,5800.0,18.5,4.0,159.0,97.0,66.0,2810.0
91,22.7,0,2.3,114.0,5400.0,15.8,5.0,190.0,104.0,67.0,2985.0
92,26.7,5,2.4,168.0,6200.0,19.3,5.0,184.0,105.0,69.0,3245.0

In [10]:
# mhd = pd.get_dummies(data=dff,drop_first=True
dff= dff.drop(['Cylinders'],axis =1)
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Price               93 non-null     float64
 1   EngineSize          93 non-null     float64
 2   Horsepower          93 non-null     float64
 3   RPM                 93 non-null     float64
 4   Fuel.tank.capacity  93 non-null     float64
 5   Passengers          93 non-null     float64
 6   Length              93 non-null     float64
 7   Wheelbase           93 non-null     float64
 8   Width               93 non-null     float64
 9   Weight              93 non-null     float64
dtypes: float64(10)
memory usage: 7.4 KB

In [11]:
X = dff.drop('Price',axis=1)
y = dff['Price']

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3,random_state=2)

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()